version: '3'

services:
  lab:
    build: .
    volumes:
     - ./code:/home/jovyan/work/code
     - ./images:/home/jovyan/work/images
     - ./notebooks:/home/jovyan/work/notebooks
     - ./notes:/home/jovyan/work/notes
     - ./data:/home/jovyan/work/data
     - ./misc:/home/jovyan/work/misc
    ports:
      - 8889:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh 
